{
    # Default all-in-one configs
    'seed': 0, 
    'vit': 'vit_base_patch16_224', 
    'shared_embedding_dim': 512, 
    'hidden_size': 768, 
    'num_heads': 12, 
    'num_layers': 12, 
    'drop_rate': 0.1, 
    'image_size': 224,
    'max_text_len': 40,
    # Fixed training settings
    'val_check_interval': 1.0, 
    'optim_type': 'adamw', 
    'learning_rate': 0.0000003, 
    'weight_decay': 0.4,
    'decay_power': 1, 
    'warmup_steps': 0.1, 
    'end_lr': 0,
    'lr_mult': 1,
    'num_nodes': 1,
    'num_workers': 15,
    'precision': 16,
    'fast_dev_run': False,
    # Logging
    'exp_name': 'multimodal_base',
    'log_dir': 'tmp', 
    # Model settings
    'use_clip': False,
    'use_git': False,
    'num_frames': 3,
    # Training settings
    'batch_size': 64,
    'per_gpu_batchsize': 16,
    'num_gpus': 2, 
    'max_epoch': 50,
    'test_only': True, 
    # Masking settings
    'masking_type': 'image',
    'masking_prob': 0.0,
    # Loading models
    'load_path': '/dvmm-filer3a/users/kevin/all-in-one-main/pretrained/all-in-one-base.ckpt',
    # 'load_path': '/home/kevin/nlp_2_2024_2_19/version_0/checkpoints/epoch=15-step=111647.ckpt',
    #'load_path': /dvmm-filer3a/users/kevin/temporal-relations/result/half_mask_2024_2_3/version_0/checkpoints/epoch=24-step=174449.ckpt,
    #'load_path': '/dvmm-filer3a/users/kevin/temporal-relations/result/multimodal_2024_3_16/version_0/checkpoints/epoch=31-step=223295.ckpt',
    # 'load_path': '/dvmm-filer3a/users/kevin/temporal-relations/tmp/one_modality_2024_3_13/version_1/checkpoints/epoch=25-step=181427.ckpt',
    'resume_from': None
}