config:
  batch_size: 32
  decay_power: 1
  drop_rate: 0.1
  end_lr: 0
  exp_name: clip
  fast_dev_run: false
  hidden_size: 768
  image_size: 224
  learning_rate: 1.0e-07
  load_path: /dvmm-filer3a/users/kevin/temporal-relations/result/clip_2024_3_30/version_0/checkpoints/epoch=10-step=76757.ckpt
  log_dir: tmp
  lr_mult: 1
  masking_prob: 0.0
  masking_type: one_modality
  max_epoch: 30
  max_text_len: 40
  num_frames: 12
  num_gpus: 2
  num_heads: 12
  num_layers: 12
  num_nodes: 1
  num_workers: 40
  optim_type: adamw
  per_gpu_batchsize: 32
  precision: 16
  resume_from: None
  seed: 0
  shared_embedding_dim: 512
  test_only: true
  use_clip: true
  use_git: false
  val_check_interval: 1.0
  vit: vit_base_patch16_224
  vocab_size: 30522
  warmup_steps: 0.1
  weight_decay: 1.0
